import fs from 'fs';
const S = JSON.parse(fs.readFileSync('src/兽血沸腾/tavern-cards-state.json', 'utf8'));
const m = S.entryManifest;
console.log('══ entryManifest 类型 ══');
for (const t of Object.keys(m)) console.log(`  ${t.padEnd(8)} ${Object.keys(m[t]).length}`);
console.log('\n角色 前 8 键: ' + Object.keys(m['角色']).slice(0, 8).join('、'));
console.log('NPC 前 8 键: ' + Object.keys(m['NPC']).slice(0, 8).join('、'));
console.log('\n══ 角色/凝玉_基础信息 ══');
console.log(JSON.stringify(m['角色']['凝玉_基础信息'], null, 1));
console.log('\n══ 角色/凝玉_性格调色盘 ══');
console.log(JSON.stringify(m['角色']['凝玉_性格调色盘'], null, 1));
const k = Object.keys(m['NPC'])[0];
console.log(`\n══ NPC/${k} ══`);
console.log(JSON.stringify(m['NPC'][k], null, 1));
console.log('\n══ typeLists ══');
console.log(JSON.stringify(S.typeLists, null, 1));
console.log('\n══ strategyThresholds.角色 ══');
console.log(JSON.stringify(S.strategyThresholds['角色'], null, 1));
console.log('\n══ partOrder ══');
console.log(JSON.stringify(S.partOrder, null, 1));
